// =============================================================================
// CRAFT PLATFORM — MASTER TAXONOMY (13 CATEGORIES, SUB-CATEGORIES, TAGS & TOOLS)
// =============================================================================

export interface CategoryTaxonomyItem {
  id: string;
  name: string;
  shortName: string;
  subCategories: string[];
  tags: string[];
  tools: string[];
}

export const MASTER_TAXONOMY: CategoryTaxonomyItem[] = [
  {
    id: "ui",
    name: "User Interface Design (UI)",
    shortName: "UI",
    subCategories: [
      "Web Design",
      "Mobile App Design",
      "Dashboard & SaaS Design",
      "Design Systems",
      "Responsive Web",
      "Smartwatch & Wearables UI",
      "Landing Pages",
      "E-commerce UI",
      "Web3 & Crypto UI",
    ],
    tags: [
      "Auto-layout",
      "Design Tokens",
      "Component Architecture",
      "8-Point Grid",
      "Semantic Variables",
      "Dark Mode",
      "UI Kits",
      "Micro-interactions",
      "Developer Handoff",
      "Typography Scale",
      "Atomic Design",
      "Glassmorphism",
      "Neumorphism",
      "Bento Grid",
      "Material Design",
      "Human Interface Guidelines (HIG)",
      "Fluid Typography",
      "Accessibility (A11y)",
      "Prototyping",
    ],
    tools: [
      "Figma",
      "Sketch",
      "Adobe XD",
      "Framer",
      "Penpot",
      "Zeplin",
      "VS Code",
      "Webflow",
      "Relume",
      "Anima",
      "Lunacy",
      "InVision",
    ],
  },
  {
    id: "ux",
    name: "User Experience Design (UX)",
    shortName: "UX",
    subCategories: [
      "UX Research",
      "Information Architecture",
      "Interaction Design",
      "Usability Testing",
      "UX Writing & Content Strategy",
      "Service Design",
      "Customer Experience (CX)",
    ],
    tags: [
      "Wireframing",
      "User Flows",
      "User Personas",
      "Journey Mapping",
      "Heuristic Evaluation",
      "Card Sorting",
      "Tree Testing",
      "Qualitative Research",
      "Quantitative Research",
      "A/B Testing",
      "Empathy Maps",
      "Service Blueprinting",
      "Competitor Analysis",
      "UX Audit",
      "Cognitive Bias",
      "Contextual Inquiry",
      "Task Analysis",
    ],
    tools: [
      "FigJam",
      "Miro",
      "Maze",
      "Hotjar",
      "Optimal Workshop",
      "UserTesting",
      "Dovetail",
      "Notion",
      "Whimsical",
      "Balsamiq",
      "Typeform",
      "Lookback",
      "Microsoft Clarity",
    ],
  },
  {
    id: "graphic-design",
    name: "Graphic Design",
    shortName: "Graphic",
    subCategories: [
      "Print Design",
      "Editorial & Magazine Design",
      "Poster Design",
      "Packaging Design",
      "Marketing Collateral",
      "Social Media Graphics",
      "Book Design",
      "Album Art",
      "Environmental Graphics",
    ],
    tags: [
      "Layout Composition",
      "Grid Systems",
      "Color Theory",
      "Pre-press",
      "Print Production",
      "Visual Hierarchy",
      "Typography Hierarchy",
      "Image Manipulation",
      "Photo Retouching",
      "Social Media Templates",
      "Brochures",
      "Billboards",
      "Merch Design",
      "Die-cut",
      "Halftone",
      "CMYK",
      "Bleed & Margins",
    ],
    tools: [
      "Adobe Illustrator",
      "Adobe Photoshop",
      "Adobe InDesign",
      "CorelDRAW",
      "Canva",
      "Affinity Designer",
      "Affinity Photo",
      "Photopea",
      "QuarkXPress",
    ],
  },
  {
    id: "brand-identity",
    name: "Brand Identity",
    shortName: "Brand",
    subCategories: [
      "Logo Design",
      "Brand Guidelines",
      "Visual Strategy",
      "Rebranding",
      "Custom Typography",
      "Brand Collateral",
      "Corporate Identity",
      "Event Branding",
    ],
    tags: [
      "Brand Archetypes",
      "Moodboards",
      "Brand Marks",
      "Monograms",
      "Style Guides",
      "Brand Assets",
      "Color Palettes",
      "Brand Positioning",
      "Wordmarks",
      "Emblems",
      "Brand Strategy",
      "Tone of Voice",
      "Mascot Design",
      "Brand Touchpoints",
      "Visual Language",
      "Pattern Design",
    ],
    tools: [
      "Adobe Illustrator",
      "Adobe Photoshop",
      "Adobe InDesign",
      "FontForge",
      "Glyphs",
      "Milanote",
      "CorelDRAW",
      "Pinterest",
    ],
  },
  {
    id: "motion-design",
    name: "Motion Design",
    shortName: "Motion",
    subCategories: [
      "Kinetic Typography",
      "Title Sequences",
      "Broadcast Design",
      "UI Animation",
      "Explainer Videos",
      "Promo Graphics",
      "Logo Animation",
      "Product Animation",
    ],
    tags: [
      "Keyframing",
      "Easing Curves",
      "Transitions",
      "Compositing",
      "Motion Tracking",
      "Visual Effects (VFX)",
      "Lower Thirds",
      "Dynamic Graphics",
      "Rotoscoping",
      "2.5D Animation",
      "Parallax",
      "Liquid Motion",
      "HUD Design",
      "Character Rigging (Motion)",
      "Loop Animation",
      "Storyboarding",
    ],
    tools: [
      "Adobe After Effects",
      "Premiere Pro",
      "Cinema 4D",
      "DaVinci Resolve",
      "Rive",
      "LottieFiles",
      "Cavalry",
      "Nuke",
      "Apple Motion",
      "Jitter",
      "Principle",
      "Spline",
    ],
  },
  {
    id: "3d-design",
    name: "3D Design",
    shortName: "3D",
    subCategories: [
      "3D Modeling",
      "Architectural Visualization",
      "Environment Design",
      "3D Rendering",
      "Spatial Design",
      "Character Sculpting",
      "Product Visualization",
      "Abstract 3D",
    ],
    tags: [
      "Texturing",
      "Shading",
      "Lighting",
      "UV Mapping",
      "Photorealism",
      "Low Poly",
      "High Poly",
      "Hard Surface Modeling",
      "Ray Tracing",
      "Organic Sculpting",
      "Retopology",
      "Rigging",
      "Procedural Generation",
      "Fluid Simulations",
      "PBR Materials",
      "ArchViz",
      "Matte Painting",
      "Voxel Art",
    ],
    tools: [
      "Blender",
      "Autodesk Maya",
      "Cinema 4D",
      "3ds Max",
      "ZBrush",
      "KeyShot",
      "Unreal Engine",
      "Substance 3D Painter",
      "Substance 3D Designer",
      "Houdini",
      "Marvelous Designer",
      "V-Ray",
      "OctaneRender",
    ],
  },
  {
    id: "illustration",
    name: "Illustration",
    shortName: "Illustration",
    subCategories: [
      "Vector Illustration",
      "Character Design",
      "Editorial Illustration",
      "Book & Cover Illustration",
      "Iconography",
      "Concept Art",
      "Medical Illustration",
      "Technical Illustration",
    ],
    tags: [
      "Digital Sketching",
      "Line Art",
      "Isometric Illustration",
      "Flat Illustration",
      "Narrative Art",
      "Spot Illustrations",
      "Digital Painting",
      "Children's Book",
      "Comic Layouts",
      "Storyboarding",
      "Watercolor",
      "Gouache Digital",
      "Cyberpunk Art",
      "Fantasy Art",
      "Manga/Anime Style",
      "Doodle",
      "Silhouette",
    ],
    tools: [
      "Procreate",
      "Adobe Illustrator",
      "Adobe Fresco",
      "Clip Studio Paint",
      "Affinity Designer",
      "Wacom (Hardware)",
      "PaintTool SAI",
      "Corel Painter",
      "Krita",
      "MediBang Paint",
    ],
  },
  {
    id: "game-design",
    name: "Game Design",
    shortName: "Game",
    subCategories: [
      "Level Design",
      "Game Mechanics",
      "Character Concept Art",
      "Environment Concept Art",
      "UI for Games",
      "Systems Design",
      "Quest/Narrative Design",
    ],
    tags: [
      "Game Loop",
      "Playtesting",
      "Sprite Sheets",
      "Pixel Art",
      "Isometric Design",
      "RPG Mechanics",
      "FPS",
      "Casual Games",
      "World Building",
      "Balancing",
      "Economy Design",
      "HUDs",
      "Game Flow",
      "Loot Systems",
      "Concept Arting",
      "Low Poly Assets",
    ],
    tools: [
      "Unity",
      "Unreal Engine",
      "Godot",
      "Construct",
      "GameMaker",
      "Spine 2D",
      "Tiled",
      "RPG Maker",
      "Blender",
      "Aseprite",
    ],
  },
  {
    id: "spatial-design",
    name: "AR/VR & Spatial Design",
    shortName: "AR/VR",
    subCategories: [
      "Augmented Reality (AR)",
      "Virtual Reality (VR)",
      "Mixed Reality (MR)",
      "Metaverse Environments",
      "Spatial Interfaces",
      "AR Filters & Lenses",
    ],
    tags: [
      "Spatial Computing",
      "Haptics",
      "Immersive Experience",
      "Head-Mounted Displays (HMD)",
      "360 Environments",
      "Volumetric Video",
      "3D UI",
      "WebXR",
      "Hand Tracking",
      "Passthrough",
      "Scene Understanding",
      "Virtual Tours",
      "Raycasting",
      "Spatial Grids",
    ],
    tools: [
      "Unity",
      "Unreal Engine",
      "Spark AR",
      "Lens Studio",
      "Spline",
      "Reality Composer",
      "A-Frame",
      "Bezi",
      "ShapesXR",
      "8th Wall",
    ],
  },
  {
    id: "industrial-design",
    name: "Industrial & Physical Product Design",
    shortName: "Product",
    subCategories: [
      "Consumer Electronics",
      "Furniture Design",
      "Automotive Design",
      "Packaging Form Design",
      "Sustainable Design",
      "Toy Design",
      "Wearable Technology",
    ],
    tags: [
      "Ergonomics",
      "Rapid Prototyping",
      "Manufacturing Processes",
      "CMF (Color, Materials, Finish)",
      "3D Printing",
      "Injection Molding",
      "Blueprints",
      "Sustainability",
      "Concept Sketching",
      "CAD Drafting",
      "Tolerancing",
      "User-Centered Hardware",
      "Form Factor",
      "Industrial Blueprinting",
    ],
    tools: [
      "SolidWorks",
      "Rhino",
      "Fusion 360",
      "AutoCAD",
      "KeyShot",
      "Shapr3D",
      "CATIA",
      "PTC Creo",
      "Onshape",
      "Alias",
    ],
  },
  {
    id: "animation",
    name: "Animation (2D & Traditional)",
    shortName: "Animation",
    subCategories: [
      "Character Animation",
      "Cel Animation",
      "Stop Motion",
      "Cut-out Animation",
      "Storyboarding & Animatics",
      "Motion Comics",
    ],
    tags: [
      "Rigging",
      "Keyframing",
      "Onion Skinning",
      "Tweening",
      "Lip Syncing",
      "Frame-by-Frame",
      "Puppet Rigging",
      "Background Painting",
      "Walk Cycle",
      "Smear Frames",
      "Pose-to-Pose",
      "Straight Ahead Animation",
      "Timing and Spacing",
      "Squash and Stretch",
    ],
    tools: [
      "Toon Boom Harmony",
      "TVPaint",
      "Adobe Animate",
      "Moho",
      "Krita",
      "OpenToonz",
      "RoughAnimator",
      "Spine 2D",
      "Dragonframe",
    ],
  },
  {
    id: "type-design",
    name: "Type Design & Lettering",
    shortName: "Type",
    subCategories: [
      "Font Creation",
      "Calligraphy",
      "Hand Lettering",
      "Custom Logotypes",
      "Typography Systems",
      "Signage",
    ],
    tags: [
      "Kerning",
      "Tracking",
      "Ligatures",
      "Serifs",
      "Sans-Serifs",
      "Variable Fonts",
      "Glyphs",
      "Script Lettering",
      "Font Hinting",
      "Display Fonts",
      "Text Fonts",
      "Monospaced",
      "Multilingual Support",
      "Typographic Scales",
      "Ascenders/Descenders",
    ],
    tools: [
      "Glyphs",
      "FontForge",
      "RoboFont",
      "FontLab",
      "Procreate",
      "Adobe Illustrator",
      "Calligraphr",
      "BirdFont",
    ],
  },
  {
    id: "presentation-design",
    name: "Presentation & Information Design",
    shortName: "Presentation",
    subCategories: [
      "Pitch Decks",
      "Corporate Presentations",
      "Infographics",
      "Data Visualization",
      "Webinar Slides",
      "Annual Reports",
    ],
    tags: [
      "Storytelling",
      "Slide Layouts",
      "Master Slides",
      "Chart Design",
      "Visual Hierarchy",
      "Data Mapping",
      "Executive Summaries",
      "Dashboard UI",
      "Visual Storytelling",
      "Isometric Infographics",
      "Typography Focus",
      "Transition Animations",
    ],
    tools: [
      "Keynote",
      "PowerPoint",
      "Google Slides",
      "Pitch",
      "Canva",
      "Tableau",
      "Prezi",
      "Tome",
      "Beautiful.ai",
      "Flourish",
      "Infogram",
    ],
  },
];

// Flat lists and helpers
export const ALL_CATEGORY_NAMES = MASTER_TAXONOMY.map((c) => c.name);

export const ALL_SUB_CATEGORIES = Array.from(
  new Set(MASTER_TAXONOMY.flatMap((c) => c.subCategories))
);

export const ALL_TAGS = Array.from(
  new Set(MASTER_TAXONOMY.flatMap((c) => c.tags))
);

export const ALL_TOOLS = Array.from(
  new Set(MASTER_TAXONOMY.flatMap((c) => c.tools))
);

// Map old abbreviations / partial names to current full categories
const CATEGORY_ALIASES: Record<string, string> = {
  UI: "User Interface Design (UI)",
  UX: "User Experience Design (UX)",
  Brand: "Brand Identity",
  Photo: "Graphic Design",
  Editorial: "Graphic Design",
  "3D & Motion": "3D Design",
  Product: "Industrial & Physical Product Design",
  Architecture: "3D Design",
  Type: "Type Design & Lettering",
};

export function normalizeCategory(categoryName?: string): string {
  if (!categoryName) return MASTER_TAXONOMY[0].name;
  if (CATEGORY_ALIASES[categoryName]) {
    return CATEGORY_ALIASES[categoryName];
  }
  const match = MASTER_TAXONOMY.find(
    (c) =>
      c.name.toLowerCase() === categoryName.toLowerCase() ||
      c.shortName.toLowerCase() === categoryName.toLowerCase() ||
      c.id.toLowerCase() === categoryName.toLowerCase()
  );
  return match ? match.name : categoryName;
}

export function getCategoryTaxonomy(categoryName?: string): CategoryTaxonomyItem | undefined {
  if (!categoryName) return MASTER_TAXONOMY[0];
  const normalized = normalizeCategory(categoryName);
  return MASTER_TAXONOMY.find((c) => c.name === normalized);
}

export function getSubCategoriesForCategory(categoryName?: string): string[] {
  const tax = getCategoryTaxonomy(categoryName);
  return tax ? tax.subCategories : [];
}

export function getTagsForCategory(categoryName?: string): string[] {
  const tax = getCategoryTaxonomy(categoryName);
  return tax ? tax.tags : ALL_TAGS.slice(0, 15);
}

export function getToolsForCategory(categoryName?: string): string[] {
  const tax = getCategoryTaxonomy(categoryName);
  return tax ? tax.tools : ALL_TOOLS.slice(0, 12);
}
